version: "3.9"

services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: always

  text_indexing_service:
    build: ./services/text_indexing_service
    ports:
      - "8002:8000"
    depends_on:
      - qdrant

  visual_indexing_service:
    build: ./services/visual_indexing_service
    ports:
      - "8003:8000"
    depends_on:
      - qdrant

  ingestion_service:
    build: ./services/ingestion_service
    ports:
      - "8001:8000"
    depends_on:
      - text_indexing_service
      - visual_indexing_service

  retrieval_service:
    build: ./services/retrieval_service
    ports:
      - "8004:8000"
    depends_on:
      - qdrant

  generation_service:
    build: ./services/generation_service
    ports:
      - "8005:8000"

  api_gateway:
    build: ./services/api_gateway
    ports:
      - "8006:8000"
    depends_on:
      - retrieval_service
      - generation_service